SUPABASE_URL = "https://ktfbfqdwhetjjlhjcyqq.supabase.co/rest/v1/"
SUPABASE_KEY = "sb_publishable_HNzmTyr-Qd-cWDV1OsMVaA_LzUaZgYO"
# SUPABASE_PUBLISHABLE_KEY = ""

DEV_MODE = true
DEV_LOGIN_EMAIL = "69@69.no"
DEV_LOGIN_PASSWORD = "69"